title: Задачи
href: index.md
items: 
  - name: Обзор методов
    href: index.md
  - name: Новая карточка задач
    href: tasks-new.md    
  - name: Поля задачи
    href: fields.md
  - name: Поля задачи v 3.0
    href: fields-rest-v3.md
  - name: Добавить задачу
    href: tasks-task-add.md
  - name: Добавить задачу v 3.0
    href: tasks-task-add-rest-v3.md
  - name: Изменить задачу
    href: tasks-task-update.md
  - name: Изменить задачу v 3.0
    href: tasks-task-update-rest-v3.md
  - name: Получить задачу по идентификатору
    href: tasks-task-get.md
  - name: Получить задачу по идентификатору v 3.0
    href: tasks-task-get-rest-v3.md
  - name: Получить список задач
    href: tasks-task-list.md
  - name: Получить список задач v 3.0
    href: tasks-task-list-rest-v3.md
  - name: Удалить задачу
    href: tasks-task-delete.md
  - name: Удалить задачу v 3.0
    href: tasks-task-delete-rest-v3.md
  - name: Получить список полей задачи
    href: tasks-task-get-fields.md
  - name: Получить список полей задачи v 3.0
    href: tasks-task-field-list.md
  - name: Получить описание поля задачи
    href: tasks-task-field-get.md
  - name: Проверить доступ к задаче
    href: tasks-task-get-access.md
  - name: Проверить доступ к задаче v 3.0
    href: tasks-task-access-get.md
  - name: Получить список полей прав доступа
    href: tasks-task-access-field-list.md
  - name: Получить описание поля прав доступа
    href: tasks-task-access-field-get.md
  - name: Прикрепить файлы к задаче
    href: tasks-task-files-attach.md
  - name: Прикрепить файлы к задаче v 3.0
    href: tasks-task-file-attach.md
  - name: Получить список полей файлов задачи
    href: tasks-task-file-field-list.md
  - name: Получить описание поля файлов задачи
    href: tasks-task-file-field-get.md
  - name: Отправить сообщение в чат задачи
    href: tasks-task-chat-message-send.md
  - name: Получить список полей сообщения чата задачи
    href: tasks-task-chat-message-field-list.md
  - name: Получить описание поля сообщения чата задачи
    href: tasks-task-chat-message-field-get.md
  - name: Получить счетчики пользователя
    href: tasks-task-counters-get.md
  - name: Делегировать задачу
    href: tasks-task-delegate.md
  - name: Принять задачу
    href: tasks-task-approve.md
  - name: Отклонить задачу
    href: tasks-task-disapprove.md
  - name: История задачи
    href: tasks-task-history-list.md
  - name: Создать связь между задачами
    href: task-dependence-add.md
  - name: Удалить связь между задачами
    href: task-dependence-delete.md
  - name: Смена статуса задачи
    include:
      path: status/b24-toc.yaml
      mode: link
  - name: Действия пользователя по задаче
    include:
      path: user-actions/b24-toc.yaml
      mode: link
  - name: Результат задачи
    include:
      path: result/b24-toc.yaml
      mode: link
  - name: События
    include:
      path: events-tasks/b24-toc.yaml
      mode: link
  - name: Чек-листы
    include:
      path: checklist-item/b24-toc.yaml
      mode: link
  - name: Комментарии
    include:
      path: comment-item/b24-toc.yaml
      mode: link
  - name: Затраченное время
    include:
      path: elapsed-item/b24-toc.yaml
      mode: link
  - name: Пользовательские поля
    include:
      path: user-field/b24-toc.yaml
      mode: link
  - name: Стадии канбана и «Моего плана»
    include:
      path: stages/b24-toc.yaml
      mode: link
  - name: Задачи в «Плане на день»
    include:
      path: planner/b24-toc.yaml
      mode: link
  - name: Потоки
    include:
      path: flow/b24-toc.yaml
      mode: link
  - name: Шаблоны
    include:
      path: template/b24-toc.yaml
      mode: link
  - name: Устаревшее
    include:
      path: deprecated/b24-toc.yaml
      mode: link
